### ISSUE TITLE
Library/package versions?

### ISSUE THREAD

**Issue by jfsantos** [santi-pdp/segan#1]
First of all, thanks for sharing the code and congratulations for the results! 

I am trying to train the model on my machine but I am getting segfaults on Tensorflow, which I believe might be due to a difference in the version. What are the versions of the packages you are using on your environment to run this? Could you provide a `requirements.txt` file for the environment you are using? It can be generated by running `pip freeze > requirements.txt`.

**Comment by santi-pdp** [comment]
Hi @jfsantos !

I have pushed a `requirements.txt` file, thanks for pointing out the lack of it. There you'll see the TF version (0.12.1) plus few other dependencies. Hope that solves it.

**Comment by jfsantos** [comment]
Thank you very much! Installing Tensorflow 0.12.1 fixed the issues I was having.
