### ISSUE TITLE
bit depth is not same for output

### ISSUE THREAD

**Issue by dankorg** [santi-pdp/segan#10]
If the input wav file is 16bit, using this framework v1.1, I get output enhanced wav at 32bit, instead of 16bit. How do I fix this to get output as 16bit? 

The rest is all fine, mono and 16kHz.

Thanks

**Comment by santi-pdp** [comment]
Hi @dankorg ,

you are right, it's because G's output is continuous, hence float32. We converted them with sox when required: `sox <in_filename>.wav -b 16 <out_filename>.wav`

Regards
