### ISSUE TITLE
no progress?

### ISSUE THREAD

**Issue by amhajavi** [santi-pdp/segan#18]
Hi I have tried your code without tensorflow_gpu and the plain tensorflow only and it seems to be stuck at the stage where it says "Sampling some wavs to store sample references..." how long does it take to sample wavs ? How should I know if it is working. 

thanks in advance

**Comment by santi-pdp** [comment]
It works quite immediately to me printing the typical output when I set CUDA_VISIBLE_DEVICES="" (None):
```
Sampling some wavs to store sample references...
sample noisy shape:  (150, 16384)
sample wav shape:  (150, 16384)
sample z shape:  (150, 8, 1024)
total examples in TFRecords data/segan.tfrecords: 48650
Batches per epoch:  324
```
The batches are computed in ~120 seconds with `batch_size=150`.
You can see your process in unix with `top` command, checking if you python process is consuming cpu and memory.

**Comment by santi-pdp** [comment]
If you need a timing measure for my desktop computer: `~0.49s`

**Comment by amhajavi** [comment]
Awesome thanks now I see my problem here. I have my audio files wrong. They where all in capital letter extensions "WAV" and it could not find any of files. Thank you for your response I may have been chasing my tail here for along time for this. 

Now it's running like a charm. Thanks for the great work by the way.
