### ISSUE TITLE
Using data from training

### ISSUE THREAD

**Issue by amhajavi** [santi-pdp/segan#19]
Hello again, 

I have had an issue with training before which with your great help I surpassed it and now encounter a new issue regarding the matter. 

I have trained a new set of wav files and gathered and saved specified weights with the command:
`CUDA_VISIBLE_DEVICES="" python main.py --init_noise_std 0. --save_path segan_allbiased_preemph \
                                          --init_l1_weight 100. --batch_size 100 --g_nl prelu \
                                          --save_freq 50 --preemph 0.95 --epoch 86 --bias_deconv True \
                                          --bias_downconv True --bias_D_conv True`

Now I'm trying to regenerate a wav file with the command: 
`CUDA_VISIBLE_DEVICES="" python main.py --init_noise_std 0. --save_path segan_allbiased_preemph \
                                       --batch_size 100 --g_nl prelu --weights segan_allbiased_preemph --preemph 0.95\
                                      --test_wav 'Test\ Folder/Source/split_008F01001.WAV.wav' --clean_save_path 'Test\ Folder/Target'`

And encounter the error saying:
`Unable to open table file segan_allbiased_preemph/train: Failed precondition: segan_allbiased_preemph/train: perhaps your file is in a different file format and you need to use a different restore operator?`

Where did I go wrong and how can I do it correctly?

**Comment by amhajavi** [comment]
Sorry NOW I get the concept I have to specify the checkpoint. I always go head first to asking then try to look around the code.

**Comment by andreaschandra** [comment]
can you tell me how to solve the problem @amhajavi ?
