### ISSUE TITLE
session.run() does not proceed

### ISSUE THREAD

**Issue by gmkim90** [santi-pdp/segan#22]
When executing train_segan.sh, programs stops in model.py line 
`sample_noisy, sample_wav, sample_z = self.sess.run([self.gtruth_noisy[0], self.gtruth_wavs[0], self.zs[0]])
`
and does not proceed at all.

Could you provide possible reason or solution regarding this issue?

I really appreciate any comments.

Thank you.

**Comment by santi-pdp** [comment]
Hi there, What do you mean "it stops"? Does it crash? Is there any error that you can paste here? Couple possible reasons you may be having at this point are:

1) is your TensorFlow version <= 0.12?
2) Have you processed the data prior to running train?

Regards

**Comment by gmkim90** [comment]
What I mean "stop" is the program does not proceeds from line above. And termination signal (ctrl + c) does not work. It takes more than 8hours.

1. My TF version is 0.12 (by pip install -r requirements.txt)
2. I built data by running ./prepare_data.sh.

**Comment by keikawai** [comment]
SEGAN I ran was a similar phenomenon. Thinking of a thread problem as well
I thought that it would be something to help and tried printing as below.
We appreciate your reference.
=================================================
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(coord=coord)

        for threadobj in threads:
            print(threadobj)

        print('Sampling some wavs to store sample references...')
        # Hang onto a copy of wavs so we can feed the same one every time
        # we store samples to disk for hearing
        # pick a single batch
        print(self.sess)
        print(self.gtruth_noisy[0])
        print(self.gtruth_wavs[0])
        print(self.zs[0])

        sample_noisy, sample_wav, sample_z = self.sess.run([self.gtruth_noisy[0],
                                  self.gtruth_wavs[0],
                                  self.zs[0]])
================================================

<Thread(Thread-2, started daemon 139715554572032)>
<Thread(Thread-3, started daemon 139715546179328)>
<Thread(Thread-4, started daemon 139715530716928)>
<Thread(Thread-5, started daemon 139715522324224)>
<Thread(Thread-6, started daemon 139715498997504)>
<Thread(Thread-7, started daemon 139715151918848)>
<Thread(Thread-8, started daemon 139715143526144)>
<Thread(Thread-9, started daemon 139715135133440)>
Sampling some wavs to store sample references...
<tensorflow.python.client.session.Session object at 0x7f12c4357b10>
Tensor("device_0/wav_and_noisy:1", shape=(2, 16384), dtype=float32, device=/device:GPU:0)
Tensor("device_0/wav_and_noisy:0", shape=(2, 16384), dtype=float32, device=/device:GPU:0)
Tensor("device_0/g_ae_1/z:0", shape=(2, 8, 1024), dtype=float32, device=/device:GPU:0)

**Comment by jutn7537** [comment]
Hi, I am facing the same problems, how is it addressed? 
Thanks
