### ISSUE TITLE
How to get evaluation metric? : PESQ, CSIG, CBAK, COVL, SSNR

### ISSUE THREAD

**Issue by gmkim90** [santi-pdp/segan#24]
After denoising the speech mixture, how to get evaluation metric you used in paper?

Could you provide how you calculate this measure?

**Comment by zhengge** [comment]
@gmkim90 
I have the same question.
Do you get evaluation metric used in paper?

**Comment by Lerry123** [comment]
hello，Do you have the code about CSIG, CBAK, COVL?If you have,Could you share with me?

**Comment by ssrp** [comment]
@lifelongeek Since you have closed the issue, could you please share the code/reference with us?
