### ISSUE TITLE
Variable gamma does not exist or was not created with tf.get_variable

### ISSUE THREAD

**Issue by rafaelvalle** [santi-pdp/segan#27]
I'm python3 and tesorflow 1.3.0. and getting the error below when executing line 149 on model.py
Any thoughts on how to fix it? Note that the block at which it happens changes, can be 1, 5, etc...

    ValueError: Variable d_model/d_block_5/d_vbn_r/gamma/RMSProp/ does not exit, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by nithishdivakar** [comment]
Same error here.

**Comment by zhengge** [comment]
Hi @rafaelvalle @nithishdivakar 
I have the same error.
Do you solve the problem?
Thanks!

**Comment by nithishdivakar** [comment]
@zhengge, Ya, the repo is for older version of tensorflow. If i remember correctly, it is 0.12. That solved it.
