### ISSUE TITLE
run ./train_segan.sh problem.

### ISSUE THREAD

**Issue by YingXiuHe** [santi-pdp/segan#31]
hi, when i run the ./train_segan.sh, it always stay in this interface for a long time.
i do not why, i need your help, thank you.
the code is shown below:
`num of G returned:  23
*** Discriminator summary ***
D block 0 input shape: (100, 16384, 2) *** biasing D conv *** downconved shape: (100, 8192, 16)  *** Applying VBN *** Applying Lrelu *** 
D block 1 input shape: (100, 8192, 16) *** biasing D conv *** downconved shape: (100, 4096, 32)  *** Applying VBN *** Applying Lrelu *** 
D block 2 input shape: (100, 4096, 32) *** biasing D conv *** downconved shape: (100, 2048, 32)  *** Applying VBN *** Applying Lrelu *** 
D block 3 input shape: (100, 2048, 32) *** biasing D conv *** downconved shape: (100, 1024, 64)  *** Applying VBN *** Applying Lrelu *** 
D block 4 input shape: (100, 1024, 64) *** biasing D conv *** downconved shape: (100, 512, 64)  *** Applying VBN *** Applying Lrelu *** 
D block 5 input shape: (100, 512, 64) *** biasing D conv *** downconved shape: (100, 256, 128)  *** Applying VBN *** Applying Lrelu *** 
D block 6 input shape: (100, 256, 128) *** biasing D conv *** downconved shape: (100, 128, 128)  *** Applying VBN *** Applying Lrelu *** 
D block 7 input shape: (100, 128, 128) *** biasing D conv *** downconved shape: (100, 64, 256)  *** Applying VBN *** Applying Lrelu *** 
D block 8 input shape: (100, 64, 256) *** biasing D conv *** downconved shape: (100, 32, 256)  *** Applying VBN *** Applying Lrelu *** 
D block 9 input shape: (100, 32, 256) *** biasing D conv *** downconved shape: (100, 16, 512)  *** Applying VBN *** Applying Lrelu *** 
D block 10 input shape: (100, 16, 512) *** biasing D conv *** downconved shape: (100, 8, 1024)  *** Applying VBN *** Applying Lrelu *** 
discriminator deconved shape:  (100, 8, 1024)
discriminator output shape:  (100, 1)
*****************************
Not clipping D weights
Initializing optimizers...
Initializing variables...
Sampling some wavs to store sample references...`

**Comment by YingXiuHe** [comment]
hi,i have solved this problem ,you can close this question.

**Comment by jutn7537** [comment]
我也面临的相同的问题，请问您是怎么解决的？谢谢

**Comment by Coulson1026** [comment]
> 
> 
> hi,i have solved this problem ,you can close this question.

how do you solve this problem? Now, I am facing the same problem

**Comment by YingXiuHe** [comment]
hi , i m so sorry to tell you that i was forgot the way to solve this problem ,  it's  long time for me .... so sorry .

**Comment by YingXiuHe** [comment]
> > hi,i have solved this problem ,you can close this question.
> 
> how do you solve this problem? Now, I am facing the same problem

hi , i m so sorry to tell you that i was forgot the way to solve this problem , it's long time for me .... so sorry .
