### ISSUE TITLE
Compatibility with Tensorflow 1.1.0 + Python 3

### ISSUE THREAD

**Issue by lordet01** [santi-pdp/segan#5]
First of all, thank you for sharing great idea with solid implementation.

Before I reproduce this work, I got some compatibility issue with Tensorflow 1.1.0 + Python 3.

For some hours of works, I fixed some of your codes to run on Tensorflow 1.1.0 + Python 3.

Currently, it seems work very well on my machine (Win10 64bit, Anaconda 4.2.0, Tensorflow 1.1.0rc1, Python 3.5.2)

So if you don't mind, I would like to contribute my revised codes for this repository.

Thank you.

-Kwang Myung, Jeon

**Comment by santi-pdp** [comment]
Hi @lordet01,

sure! go ahead with the PR and let's see :) 

Thank you!
