### ISSUE TITLE
segan for long wav file

### ISSUE THREAD

**Issue by pbcquoc** [santi-pdp/segan#8]
Thank you for sharing this code. This is very impressive result.
But it seen to be interrupted for long wav file.
Have you had any ideal to deal with long wav file.
This is a example: https://drive.google.com/open?id=0B9_tw8OIVz2_RXctZU5pU1RNZVU

**Comment by santi-pdp** [comment]
Hi  @pbcquoc , you mean it gets interrupted where there is noise in the middle of the stream? it looks like it filters screams as noise, but it's not interrupted from working. How was the training done? (how much data?). This is an interesting example, thanks for sharing. It shouldn't matter how long the stream is, it is a memoryless model (fully conv) so regardless of the length it should filter the whole thing anyway without degrading the functionality as time goes by. 

PS: It is interesting to see the SEGAN reproduced in other languages :) nice job
